version: '3.4'

services:
  blazorpeliculas_postgres:
    hostname: blazorpeliculas_postgres
    container_name: blazorpeliculas_postgres
    ports:
        - "35432:5432"
    restart: always
    image: postgres:13
    user: root
    environment:
      ACCEPT_EULA: Y
      POSTGRES_DB: blazorpeliculas
      POSTGRES_USER: rw_dev
      POSTGRES_PASSWORD: rw_dev
      TZ: Europe/Madrid
    networks:
      - blazorpeliculas_network # remove?
    volumes:
        - blazorpeliculas_postgres_data:/var/lib/postgresql/data
  blazorpeliculas.server:
    hostname: blazorpeliculas
    container_name: blazorpeliculas
    depends_on:
        - blazorpeliculas_postgres
    image: ${DOCKER_REGISTRY-}blazorpeliculasserver
    build:
      context: .
      dockerfile: BlazorPeliculas/Server/Dockerfile
    networks:
        - blazorpeliculas_network

networks:
  blazorpeliculas_network:

volumes:
  blazorpeliculas_postgres_data:
